In [2]:
# Data Importing and Frequency Counting
import pandas as pd
import numpy as np

data = pd.read_excel('StockX-Data-Contest-2019-3.xlsx', sheet_name = 1, header = 0)

In [3]:
len(data.index)

99956

In [4]:
data[0:5]

Order Date   Brand                                   Sneaker Name  \
0 2017-09-01   Yeezy           Adidas-Yeezy-Boost-350-Low-V2-Beluga   
1 2017-09-01   Yeezy    Adidas-Yeezy-Boost-350-V2-Core-Black-Copper   
2 2017-09-01   Yeezy     Adidas-Yeezy-Boost-350-V2-Core-Black-Green   
3 2017-09-01   Yeezy       Adidas-Yeezy-Boost-350-V2-Core-Black-Red   
4 2017-09-01   Yeezy  Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017   

   Sale Price  Retail Price Release Date  Shoe Size  Buyer Region  
0      1097.0           220   2016-09-24       11.0    California  
1       685.0           220   2016-11-23       11.0    California  
2       690.0           220   2016-11-23       11.0    California  
3      1075.0           220   2016-11-23       11.5      Kentucky  
4       828.0           220   2017-02-11       11.0  Rhode Island

In [5]:
freq = data.groupby('Sneaker Name').count()
#data.groupby('Sneaker Name').count().shape
#there are 50 different shoes

freq = freq.sort_values(by = 'Brand',ascending = False)
freq

Order Date  Brand  \
Sneaker Name                                                           
adidas-Yeezy-Boost-350-V2-Butter                        11423  11423   
Adidas-Yeezy-Boost-350-V2-Beluga-2pt0                   10395  10395   
Adidas-Yeezy-Boost-350-V2-Zebra                         10110  10110   
Adidas-Yeezy-Boost-350-V2-Blue-Tint                      9297   9297   
Adidas-Yeezy-Boost-350-V2-Cream-White                    9097   9097   
Adidas-Yeezy-Boost-350-V2-Sesame                         5553   5553   
adidas-Yeezy-Boost-350-V2-Static                         4983   4983   
Adidas-Yeezy-Boost-350-V2-Semi-Frozen-Yellow             4854   4854   
Air-Jordan-1-Retro-High-Off-White-University-Blue        4635   4635   
adidas-Yeezy-Boost-350-V2-Static-Reflective              3184   3184   
Nike-Air-Presto-Off-White-Black-2018                     1884   1884   
Nike-Air-Presto-Off-White-White-2018                     1883   1883   
Nike-Air-VaporMax-Off-White-2018                         1591   1591   
Nike-Blazer-Mid-Off-White-All-Hallows-Eve                1435   1435   
Nike-Blazer-Mid-Off-White-Grim-Reaper                    1398   1398   
Nike-Zoom-Fly-Off-White-Pink                             1359   1359   
Nike-Air-VaporMax-Off-White-Black                        1313   1313   
Nike-Zoom-Fly-Off-White-Black-Silver                     1222   1222   
Nike-Air-Force-1-Low-Off-White-Volt                      1019   1019   
Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017             969    969   
Nike-Air-Force-1-Low-Off-White-Black-White                960    960   
Air-Jordan-1-Retro-High-Off-White-Chicago                 755    755   
Nike-Air-Max-90-Off-White-Black                           722    722   
Nike-Zoom-Fly-Mercurial-Off-White-Total-Orange            656    656   
Nike-Air-Max-90-Off-White-Desert-Ore                      649    649   
Nike-Zoom-Fly-Mercurial-Off-White-Black                   645    645   
Nike-Air-Max-90-Off-White                                 627    627   
Adidas-Yeezy-Boost-350-V2-Core-Black-White                621    621   
Nike-Air-Presto-Off-White                                 596    596   
Nike-Air-Max-97-Off-White                                 544    544   
Nike-Air-VaporMax-Off-White                               525    525   
Nike-Blazer-Mid-Off-White                                 501    501   
Adidas-Yeezy-Boost-350-Low-V2-Beluga                      498    498   
Nike-React-Hyperdunk-2017-Flyknit-Off-White               484    484   
Nike-Air-Force-1-Low-Off-White                            476    476   
Nike-Zoom-Fly-Off-White                                   435    435   
Nike-Air-Max-97-Off-White-Menta                           343    343   
Air-Jordan-1-Retro-High-Off-White-White                   313    313   
Adidas-Yeezy-Boost-350-V2-Core-Black-Red                  302    302   
Nike-Air-Max-97-Off-White-Black                           289    289   
Nike-Blazer-Mid-Off-White-Wolf-Grey                       288    288   
Adidas-Yeezy-Boost-350-V2-Core-Black-Copper               225    225   
Nike-Air-Max-97-Off-White-Elemental-Rose-Queen            216    216   
Adidas-Yeezy-Boost-350-V2-Core-Black-Green                196    196   
Adidas-Yeezy-Boost-350-Low-Pirate-Black-2016              122    122   
Adidas-Yeezy-Boost-350-Low-Moonrock                       100    100   
Adidas-Yeezy-Boost-350-Low-Pirate-Black-2015               95     95   
Adidas-Yeezy-Boost-350-Low-Oxford-Tan                      70     70   
Adidas-Yeezy-Boost-350-Low-Turtledove                      68     68   
Nike-Air-Force-1-Low-Virgil-Abloh-Off-White-AF100          31     31   

                                                   Sale Price  Retail Price  \
Sneaker Name                                                                  
adidas-Yeezy-Boost-350-V2-Butter                        11423         11423   
Adidas-Yeezy-Boost-350-V2-Beluga-2pt0                   10395        

In [7]:
# Create a matrix recording the degrees of transactions each model
shoes = data['Sneaker Name'].unique()
nbshoes = len(shoes)
deg = np.zeros((nbshoes,nbshoes))
shoes_code = dict(zip(list(shoes),list(range(nbshoes))))

In [8]:
i = 0
deg = np.zeros((nbshoes,nbshoes))
# rows: current one, columns: next one
# for example: 1,2 means how many times there is a purchase of 2 followed by 1
for i in range(len(data.index)):
    try:
        current = shoes_code[data.iloc[i]['Sneaker Name']]
        nextone = shoes_code[data.iloc[i+1]['Sneaker Name']]
        # link from current to nextone += 1
        deg[current,nextone] += 1.0
#         if i >= 5:
#             break
#         print(deg[current,nextone])
    except IndexError as e:
#         print(e)
        break

In [ ]:
deg

In [56]:
# where is the most frequent?
np.where(deg == np.amax(deg))
for k,v in shoes_code.items():
    if v == 37:
        print(k)

Nike-Blazer-Mid-Off-White-Grim-Reaper


In [13]:
# count how many unique shoes one shoes can lead to
deg_edge = np.count_nonzero(deg, axis = 0)
deg_edge_inv = 1/deg_edge

In [59]:
# # define P
# p = np.zeros((nbshoes,nbshoes))
# for i in range(nbshoes):
#     for j in range(nbshoes):
#         if deg[i,j] != 0:
#             p[i,j] = 1/deg[i,j]
#         else:
# #             p[i,j] = 0

In [11]:
deg_new = np.zeros(nbshoes)
deg_new = np.sum(deg,axis = 1)

In [12]:
deg_new

array([  498.,   225.,   196.,   302.,   969.,   621.,  9097., 10110.,
         100.,   627.,   596.,   525.,   755.,   501.,   122.,    70.,
          68.,    95.,  4854.,   476.,   544.,    31.,   484.,   435.,
       10395.,  9297.,  1591.,   313.,  1313.,  4635.,  1884.,  1883.,
         645.,   656., 11423.,   216.,  1435.,  1398.,  5553.,   288.,
         343.,   289.,  1222.,  1359.,  1019.,   960.,  4983.,  3183.,
         722.,   649.])

In [49]:
# calculate the probability of moving from shoe A to shoe B
deg_new_inv = 1/deg_new
deg_new_inv

array([2.00803213e-03, 4.44444444e-03, 5.10204082e-03, 3.31125828e-03,
       1.03199174e-03, 1.61030596e-03, 1.09926349e-04, 9.89119683e-05,
       1.00000000e-02, 1.59489633e-03, 1.67785235e-03, 1.90476190e-03,
       1.32450331e-03, 1.99600798e-03, 8.19672131e-03, 1.42857143e-02,
       1.47058824e-02, 1.05263158e-02, 2.06015657e-04, 2.10084034e-03,
       1.83823529e-03, 3.22580645e-02, 2.06611570e-03, 2.29885057e-03,
       9.62000962e-05, 1.07561579e-04, 6.28535512e-04, 3.19488818e-03,
       7.61614623e-04, 2.15749730e-04, 5.30785563e-04, 5.31067446e-04,
       1.55038760e-03, 1.52439024e-03, 8.75426771e-05, 4.62962963e-03,
       6.96864111e-04, 7.15307582e-04, 1.80082838e-04, 3.47222222e-03,
       2.91545190e-03, 3.46020761e-03, 8.18330606e-04, 7.35835173e-04,
       9.81354269e-04, 1.04166667e-03, 2.00682320e-04, 3.14169023e-04,
       1.38504155e-03, 1.54083205e-03])

In [22]:
# define transition matrix P
p = np.zeros((nbshoes,nbshoes))
for i in range(nbshoes):
    for j in range(nbshoes):
        # there is a link between shoe j to shoe i
        if deg[i,j] != 0:
            p[j,i] = deg_edge_inv[j]
        else:
            p[j,i] = 0

In [23]:
# define g
g = np.zeros((nbshoes,nbshoes))
alpha = 0.95
g = np.add(alpha*p, ((1-alpha)/nbshoes)*np.ones((nbshoes,nbshoes)))

In [24]:
g

array([[0.05377778, 0.001     , 0.001     , ..., 0.05377778, 0.001     ,
        0.001     ],
       [0.11975   , 0.11975   , 0.001     , ..., 0.001     , 0.001     ,
        0.001     ],
       [0.10655556, 0.10655556, 0.10655556, ..., 0.001     , 0.001     ,
        0.001     ],
       ...,
       [0.001     , 0.001     , 0.001     , ..., 0.476     , 0.001     ,
        0.001     ],
       [0.001     , 0.001     , 0.001     , ..., 0.001     , 0.31766667,
        0.001     ],
       [0.001     , 0.001     , 0.001     , ..., 0.001     , 0.476     ,
        0.476     ]])

In [25]:
np.sum(g, axis = 0)

array([0.5717803 , 0.45566919, 0.66263348, 0.55707792, 0.47071429,
       0.37571429, 1.21488095, 2.15624459, 0.78999611, 1.57568903,
       1.21670788, 1.38713897, 1.98550505, 1.68156358, 0.63622086,
       0.61582945, 0.25247475, 0.49108197, 1.07916667, 2.14832792,
       1.23263348, 0.55858586, 1.41880564, 1.05278832, 0.99400253,
       1.25638348, 1.0041811 , 1.6405303 , 1.59256105, 1.85164141,
       0.50388889, 0.56722222, 0.74365079, 0.70142857, 1.20015485,
       0.48126984, 0.7625    , 1.82936508, 0.60416667, 1.21865079,
       0.37571429, 0.48126984, 0.66071429, 0.66071429, 0.89108586,
       0.72555556, 1.29474359, 1.06444056, 1.26430014, 1.04263348])